apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-mydomain-local-cert
  namespace: ns1
spec:
  commonName: example.mydomain.local
  secretName: example-mydomain-local-cert
  duration: 26280h # 3 years expiray
  renewBefore: 1461h # 2 months
  dnsNames: 
    - example.mydomain.local
    - www.example.mydomain.local
  subject: 
    localities: 
      - "RoundRock"
    organizations: 
      - "saas-platform-core"
    provinces:
      - "TX"
  privateKey:
    algorithm: RSA 
    encoding: PKCS1
    size: 2048 
    rotationPolicy: Always
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io