apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: cluster-selfsigned-ca-cert
  secretName: root-ca-cert-secret
  duration: 175200h # 20 years expiray for the root ca certificate
  renewBefore: 4383h # 6 months
  subject: 
    localities: 
      - "RoundRock"
    organizations: 
      - "saas-platform-core"
    provinces:
      - "TX"
  privateKey:
    algorithm: RSA 
    encoding: PKCS1
    size: 2048 
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io